// Code generated by mockery v2.32.0. DO NOT EDIT.

package mta

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockStateOracle is an autogenerated mock type for the StateOracle type
type MockStateOracle struct {
	mock.Mock
}

type MockStateOracle_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStateOracle) EXPECT() *MockStateOracle_Expecter {
	return &MockStateOracle_Expecter{mock: &_m.Mock}
}

// CurrentState provides a mock function with given fields: ctx
func (_m *MockStateOracle) CurrentState(ctx context.Context) ([]TripUpdate, error) {
	ret := _m.Called(ctx)

	var r0 []TripUpdate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]TripUpdate, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []TripUpdate); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]TripUpdate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStateOracle_CurrentState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentState'
type MockStateOracle_CurrentState_Call struct {
	*mock.Call
}

// CurrentState is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStateOracle_Expecter) CurrentState(ctx interface{}) *MockStateOracle_CurrentState_Call {
	return &MockStateOracle_CurrentState_Call{Call: _e.mock.On("CurrentState", ctx)}
}

func (_c *MockStateOracle_CurrentState_Call) Run(run func(ctx context.Context)) *MockStateOracle_CurrentState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStateOracle_CurrentState_Call) Return(_a0 []TripUpdate, _a1 error) *MockStateOracle_CurrentState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStateOracle_CurrentState_Call) RunAndReturn(run func(context.Context) ([]TripUpdate, error)) *MockStateOracle_CurrentState_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStateOracle creates a new instance of MockStateOracle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStateOracle(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStateOracle {
	mock := &MockStateOracle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
